modLoader="javafml"
loaderVersion="[32,)"
license="GNU General Public License version 3 (GPLv3)"
issueTrackerURL="https://github.com/Tictim/Paraglider/issues"

[[mods]]
modId="paraglider"
version="${file.jarVersion}"
displayName="Paraglider"
displayURL="https://www.curseforge.com/minecraft/mc-mods/paragliders"
authors="Tictim"
description='''

'''

[[dependencies.paraglider]]
	modId="forge"
	mandatory=true
	versionRange="[32,)"
	ordering="NONE"
	side="BOTH"